args_filename = ""
base_path = "./dataset"
#base_path = "/tmp"
mode = "file"
#mode = "socket"
#events_filename_0 = "dv-runtime.sock"
events_filename_0 = "dvSave-2022_05_17_14_48_18.aedat4"
events_filename_1 = "dv-runtime2.sock"
start_c = 0.30344322344322345
deblur_only = false
events_only = false
simulate_packet_latency = true
target_latency = 500.0
optimize_c = true
optimize_c_frequency = 10
optimize_controller = false
show_display = true
show_blurred_display = false
output_fps = 1000
write_video = true
