args_filename = ""
#base_path = "/media/andrew/ExternalM2/DynamicVision"
base_path = "/tmp"
#mode = "file"
mode = "socket"
events_filename_0 = "dv-runtime.sock"
#events_filename_0 = "dvSave-2022_09_09_13_46_22.aedat4"
events_filename_1 = "dv-runtime2.sock"
start_c = 0.30344322344322345
optimize_c = 1
optimize_controller = 0
show_display = 1
show_blurred_display = 1
output_fps = 2000
write_video = 1
