base_path = "/media/andrew/ExternalM2/DynamicVision"
#base_path = "/tmp"
mode = "file"
#mode = "socket"
#events_filename_0 = "dv-runtime.sock"
events_filename_0 = "dvSave-2022_09_09_13_46_22.aedat4"
events_filename_1 = "dv-runtime2.sock"
start_c = 0.30344322344322345
deblur_only = false
events_only = false
simulate_packet_latency = true
target_latency = 500.0
optimize_c = true
optimize_controller = true
show_display = true
show_blurred_display = true
output_fps = 500
write_video = false
